version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lead_management_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: crm_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/lead_management_system?schema=public
      - JWT_SECRET=your_super_secret_jwt_key
      - JWT_REFRESH_SECRET=your_super_refresh_secret
      - EMAIL_USER=example@gmail.com
      - EMAIL_PASS=app_password
      - CLIENT_URL=http://localhost:5173
      - NODE_ENV=production
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: crm_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
      - VITE_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  pgdata:
